import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Cairo,Lexend} from 'next/font/google';
const inter = Inter({ subsets: ["latin"] });
const Cairo_init = Cairo({
  subsets:['latin'],
  weight:['200','300','700','400','500','600'],
  variable:'--cairo-font',
});
const Lexend_init = Lexend({
  subsets:['latin'],
  weight:['200','300','700','400','500','600'],
  variable:'--lexend-font',
});

export const metadata: Metadata = {
  title: "Cyparta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Cairo_init.variable} ${Lexend_init.variable}`}>{children}</body>
    </html>
  );
}
